begin;
select extensions.plan(18);
select extensions.has_schema('catalogue','catalogue schema');
select extensions.has_schema('garage','garage schema');
select extensions.has_schema('ingestion','ingestion schema');
select extensions.has_table('catalogue','manufacturers','manufacturers table');
select extensions.has_table('catalogue','machine_models','machine models table');
select extensions.has_table('catalogue','machine_variants','machine variants table');
select extensions.has_table('catalogue','facts','facts table');
select extensions.has_table('garage','organizations','organizations table');
select extensions.has_table('garage','memberships','memberships table');
select extensions.has_table('garage','machines','machines table');
select extensions.has_table('garage','machine_hours_log','hours table');
select extensions.has_table('garage','machine_service_records','service table');
select extensions.has_table('garage','machine_documents','documents table');
select extensions.has_table('garage','machine_photos','photos table');
select extensions.col_is_pk('garage','machines','id','machines primary key');
select extensions.col_is_pk('catalogue','machine_variants','id','variants primary key');
select extensions.ok(not exists(select 1 from catalogue.facts where ((machine_model_id is null)::int+(machine_variant_id is null)::int)<>1),'every catalogue fact has exactly one model/variant scope');
select extensions.ok(not exists(select 1 from pg_policies where schemaname='ingestion' and roles @> array['authenticated'::name] and (qual <> 'false' or with_check <> 'false')),'authenticated users have no ingestion-table access');
select * from extensions.finish();
rollback;