-- Repository migration for Mow Mode session and GPS tracking.
-- The corresponding migration has already been applied to Supabase production
-- as reelmow_mowing_sessions_v22.

create table if not exists garage.mowing_sessions (
  id uuid primary key default gen_random_uuid(),
  machine_id uuid not null references garage.machines(id) on delete cascade,
  started_by uuid references auth.users(id),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  status text not null default 'active' check (status = any (array['active','paused','completed','cancelled'])),
  pattern_type text check (pattern_type is null or pattern_type = any (array['straight','stripe','cross_cut','perimeter','freeform'])),
  target_speed_kph numeric check (target_speed_kph is null or target_speed_kph >= 0),
  distance_m numeric check (distance_m is null or distance_m >= 0),
  area_m2 numeric check (area_m2 is null or area_m2 >= 0),
  average_speed_kph numeric check (average_speed_kph is null or average_speed_kph >= 0),
  coverage_pct numeric check (coverage_pct is null or coverage_pct between 0 and 100),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists garage.mowing_track_points (
  id bigint generated by default as identity primary key,
  session_id uuid not null references garage.mowing_sessions(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_m numeric check (accuracy_m is null or accuracy_m >= 0),
  speed_mps numeric check (speed_mps is null or speed_mps >= 0),
  heading_deg numeric check (heading_deg is null or heading_deg >= 0 and heading_deg <= 360),
  engine_hours numeric check (engine_hours is null or engine_hours >= 0),
  is_on_track boolean,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists mowing_sessions_machine_started_idx on garage.mowing_sessions(machine_id, started_at desc);
create index if not exists mowing_sessions_status_idx on garage.mowing_sessions(status);
create index if not exists mowing_track_points_session_time_idx on garage.mowing_track_points(session_id, recorded_at);

alter table garage.mowing_sessions enable row level security;
alter table garage.mowing_track_points enable row level security;

drop policy if exists mowing_session_read on garage.mowing_sessions;
create policy mowing_session_read on garage.mowing_sessions for select to authenticated using (
  exists (select 1 from garage.machines m join garage.garages g on g.id=m.garage_id where m.id=mowing_sessions.machine_id and private.is_org_member(g.organization_id))
);
drop policy if exists mowing_session_insert on garage.mowing_sessions;
create policy mowing_session_insert on garage.mowing_sessions for insert to authenticated with check (
  exists (select 1 from garage.machines m join garage.garages g on g.id=m.garage_id where m.id=mowing_sessions.machine_id and private.has_org_role(g.organization_id,array['owner','admin','manager','operator']::garage.member_role[]))
  and (started_by is null or started_by=auth.uid())
);
drop policy if exists mowing_session_update on garage.mowing_sessions;
create policy mowing_session_update on garage.mowing_sessions for update to authenticated using (
  exists (select 1 from garage.machines m join garage.garages g on g.id=m.garage_id where m.id=mowing_sessions.machine_id and private.has_org_role(g.organization_id,array['owner','admin','manager','operator']::garage.member_role[]))
) with check (
  exists (select 1 from garage.machines m join garage.garages g on g.id=m.garage_id where m.id=mowing_sessions.machine_id and private.has_org_role(g.organization_id,array['owner','admin','manager','operator']::garage.member_role[]))
);
drop policy if exists mowing_session_delete on garage.mowing_sessions;
create policy mowing_session_delete on garage.mowing_sessions for delete to authenticated using (
  exists (select 1 from garage.machines m join garage.garages g on g.id=m.garage_id where m.id=mowing_sessions.machine_id and private.has_org_role(g.organization_id,array['owner','admin']::garage.member_role[]))
);

drop policy if exists mowing_point_read on garage.mowing_track_points;
create policy mowing_point_read on garage.mowing_track_points for select to authenticated using (
  exists (select 1 from garage.mowing_sessions s join garage.machines m on m.id=s.machine_id join garage.garages g on g.id=m.garage_id where s.id=mowing_track_points.session_id and private.is_org_member(g.organization_id))
);
drop policy if exists mowing_point_insert on garage.mowing_track_points;
create policy mowing_point_insert on garage.mowing_track_points for insert to authenticated with check (
  exists (select 1 from garage.mowing_sessions s join garage.machines m on m.id=s.machine_id join garage.garages g on g.id=m.garage_id where s.id=mowing_track_points.session_id and private.has_org_role(g.organization_id,array['owner','admin','manager','operator']::garage.member_role[]))
);
drop policy if exists mowing_point_delete on garage.mowing_track_points;
create policy mowing_point_delete on garage.mowing_track_points for delete to authenticated using (
  exists (select 1 from garage.mowing_sessions s join garage.machines m on m.id=s.machine_id join garage.garages g on g.id=m.garage_id where s.id=mowing_track_points.session_id and private.has_org_role(g.organization_id,array['owner','admin']::garage.member_role[]))
);